apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uplink-postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
