apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uplink-postgres
spec:
  serviceName: uplink-postgres
  replicas: 1
  selector:
    matchLabels:
      app: uplink-postgres
  template:
    metadata:
      labels:
        app: uplink-postgres
    spec:
      containers:
        - name: postgres
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          ports:
            - name: pg
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.passwordSecret | quote }}
                  key: password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
{{ toYaml .Values.resources | indent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
