apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uplink-minio
spec:
  serviceName: uplink-minio
  replicas: 1
  selector:
    matchLabels:
      app: uplink-minio
  template:
    metadata:
      labels:
        app: uplink-minio
    spec:
      containers:
        - name: minio
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          ports:
            - name: s3
              containerPort: 9000
            - name: console
              containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.secretName | quote }}
                  key: rootUser
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.secretName | quote }}
                  key: rootPassword
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
{{ toYaml .Values.resources | indent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
