apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uplink-redis
spec:
  serviceName: uplink-redis
  replicas: 1
  selector:
    matchLabels:
      app: uplink-redis
  template:
    metadata:
      labels:
        app: uplink-redis
    spec:
      containers:
        - name: redis
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}

          command: [ "sh", "-c" ]
          args:
            - >
              exec redis-server /etc/redis/redis.conf

          ports:
            - name: redis
              containerPort: 6379

          volumeMounts:
            - name: data
              mountPath: /data
            - name: redis-auth
              mountPath: /etc/redis
              readOnly: true

          resources:
{{ toYaml .Values.resources | indent 12 }}

      volumes:
        - name: redis-auth
          secret:
            secretName: {{ .Values.auth.secretName | quote }}
            items:
              - key: redis.conf
                path: redis.conf
              - key: users.acl
                path: users.acl

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
