apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uplink-redis
spec:
  serviceName: uplink-redis
  replicas: 1
  selector:
    matchLabels:
      app: uplink-redis
  template:
    metadata:
      labels:
        app: uplink-redis
    spec:
      containers:
        - name: redis
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          args: ["--appendonly", "yes"]
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
{{ toYaml .Values.resources | indent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
