apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.admin.externalSecretName }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: {{ .Values.secrets.storeRef.kind }}
    name: {{ .Values.secrets.storeRef.name }}
  target:
    name: {{ .Values.secrets.admin.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: adminUser
      remoteRef:
        key: {{ .Values.secrets.admin.vaultKey }}
        property: adminUser
    - secretKey: adminPassword
      remoteRef:
        key: {{ .Values.secrets.admin.vaultKey }}
        property: adminPassword
