apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: uplink-dev
  namespace: argocd
spec:
  description: Uplink dev layer
  sourceRepos:
    - '*'  # потом сузим до твоего repo URL
  destinations:
    - namespace: uplink-dev
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
